[phases.setup]
nixPkgs = ["jdk21", "maven"]

[phases.build]
cmds = [
  "export JAVA_HOME=$(dirname $(dirname $(readlink -f $(which java))))",
  "export PATH=$JAVA_HOME/bin:$PATH",
  "export MAVEN_OPTS='-Dmaven.compiler.release=21'",
  "java -version",
  "mvn -version",
  "mvn -DskipTests clean package"
]

